name: feature
description: New feature request (internal)
labels: ["feature", "triage"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line summary of the feature.
      placeholder: e.g. Add password reset via email
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe the proposed solution or approach.
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: In-scope / out-of-scope considerations.
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies / Risks
      description: Technical dependencies, risks, or constraints.
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
    validations:
      required: false
